CREATE TABLE IF NOT EXISTS rover (
  id INTEGER PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  angle INTEGER NOT NULL,
  charge INTEGER NOT NULL
);
