// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: api/contract.proto

package BAUMAN_HACK_IU5

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Simulation_BidirectionalStreaming_FullMethodName = "/example.Simulation/BidirectionalStreaming"
)

// SimulationClient is the client API for Simulation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulationClient interface {
	BidirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (Simulation_BidirectionalStreamingClient, error)
}

type simulationClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationClient(cc grpc.ClientConnInterface) SimulationClient {
	return &simulationClient{cc}
}

func (c *simulationClient) BidirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (Simulation_BidirectionalStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Simulation_ServiceDesc.Streams[0], Simulation_BidirectionalStreaming_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &simulationBidirectionalStreamingClient{stream}
	return x, nil
}

type Simulation_BidirectionalStreamingClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type simulationBidirectionalStreamingClient struct {
	grpc.ClientStream
}

func (x *simulationBidirectionalStreamingClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simulationBidirectionalStreamingClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimulationServer is the server API for Simulation service.
// All implementations must embed UnimplementedSimulationServer
// for forward compatibility
type SimulationServer interface {
	BidirectionalStreaming(Simulation_BidirectionalStreamingServer) error
	mustEmbedUnimplementedSimulationServer()
}

// UnimplementedSimulationServer must be embedded to have forward compatible implementations.
type UnimplementedSimulationServer struct {
}

func (UnimplementedSimulationServer) BidirectionalStreaming(Simulation_BidirectionalStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStreaming not implemented")
}
func (UnimplementedSimulationServer) mustEmbedUnimplementedSimulationServer() {}

// UnsafeSimulationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationServer will
// result in compilation errors.
type UnsafeSimulationServer interface {
	mustEmbedUnimplementedSimulationServer()
}

func RegisterSimulationServer(s grpc.ServiceRegistrar, srv SimulationServer) {
	s.RegisterService(&Simulation_ServiceDesc, srv)
}

func _Simulation_BidirectionalStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimulationServer).BidirectionalStreaming(&simulationBidirectionalStreamingServer{stream})
}

type Simulation_BidirectionalStreamingServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type simulationBidirectionalStreamingServer struct {
	grpc.ServerStream
}

func (x *simulationBidirectionalStreamingServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simulationBidirectionalStreamingServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Simulation_ServiceDesc is the grpc.ServiceDesc for Simulation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Simulation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.Simulation",
	HandlerType: (*SimulationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidirectionalStreaming",
			Handler:       _Simulation_BidirectionalStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/contract.proto",
}
